[package]
name = "neoshell"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.2", features = ["client"] }
memmap2 = "0.9"
wayland-egl = "0.32.11"
khronos-egl = { version = "6.0.0", features = ["dynamic"]}
libloading ="0.8.9"
glow = "0.18.0"
